### ISSUE TITLE
Why is mavlink included twice in mavsdk-windows-x64-release.zip

### ISSUE THREAD

**Issue by dzywater** [mavlink/MAVSDK#1561]
mavlink is found at
(1)mavsdk-windows-x64-release-0.43.0.zip\include\mavsdk\plugins\ftp
(2)mavsdk-windows-x64-release-0.43.0.zip\include\mavsdk\plugins\mavlink_passthrough

Both are necessary or only one or none?

**Comment by julianoes** [comment]
It makes sense that the MavlinkPassthrough plugin includes mavlink because it also exports all the mavlink headers as it basically allows to send any mavlink message.

For the Ftp plugin, the public header does not include the mavlink headers from what I can see:
https://github.com/mavlink/MAVSDK/blob/main/src/plugins/ftp/include/plugins/ftp/ftp.h
I only see it included in the implementation: https://github.com/mavlink/MAVSDK/blob/14d1878024cf7531022cdc9622039988f86bfbfe/src/plugins/ftp/ftp_impl.h#L7 which I think is fine and expected as most plugins do require mavlink in the implementation.

Does that make sense? Do you see an issue with this?

**Comment by dzywater** [comment]
> It makes sense that the MavlinkPassthrough plugin includes mavlink because it also exports all the mavlink headers as it basically allows to send any mavlink message.
> 
> For the Ftp plugin, the public header does not include the mavlink headers from what I can see:
> https://github.com/mavlink/MAVSDK/blob/main/src/plugins/ftp/include/plugins/ftp/ftp.h
> I only see it included in the implementation:
> 
> https://github.com/mavlink/MAVSDK/blob/14d1878024cf7531022cdc9622039988f86bfbfe/src/plugins/ftp/ftp_impl.h#L7
> 
> which I think is fine and expected as most plugins do require mavlink in the implementation.
> Does that make sense? Do you see an issue with this?

I'm afraid that I cannot undertand what you mean. 
I just think that mavlink need not to be included twice.
mavsdk-windows-x64-release-0.43.0.zip\include\mavsdk\plugins\ftp\mavlink folder can be deleted.
But I am not sure.

**Comment by julianoes** [comment]
>  I just think that mavlink need not to be included twice.

It should not be.

>  mavsdk-windows-x64-release-0.43.0.zip\include\mavsdk\plugins\ftp\mavlink folder can be deleted.

Aha, now I see what you mean! Let me check why that is there. I hope we can remove it.

**Comment by julianoes** [comment]
@dzywater will be fixed with https://github.com/mavlink/MAVSDK/pull/1565. Thanks for raising this.
