### ISSUE TITLE
CPU load too high when downloading logs

### ISSUE THREAD

**Issue by Katawann** [mavlink/MAVSDK#1636]
Hello !

**Description**
I download automatically the missing logs from the PX4 to my companion computer (RPi) thanks to the [LogFiles](https://mavsdk.mavlink.io/main/en/cpp/api_reference/classmavsdk_1_1_log_files.html) plugin.

**Issue**
When I'm downloading a log and I try to arm, I get the error below. You can see this behavior on [this flight review](https://logs.px4.io/plot_app?log=8180f6b3-fbfb-4a3d-9173-5101d76bfe73).
`Warning: [PreFlightCheck] Fail: CPU load too high: 98.1%`

**Context**
Pixhawk 4 with San Disk U3 32GB (same behavior with Pixhawk 5x)
Raspberry Pi 3B+ (connected with USB to the pixhawk)
PX4 v1.12.3
MAVSDK v0.48.0

**Question**
Is it possible to interrupt the [download_log_file_async](https://mavsdk.mavlink.io/main/en/cpp/api_reference/classmavsdk_1_1_log_files.html#classmavsdk_1_1_log_files_1a48712c031e204b23e00cfa28a0b1bc01) function ? Otherwise is it possible to set a parameters to reduce the ressources used by the download to avoid this kind of situation ?

Thank you in advance for your suggestion !

**Comment by julianoes** [comment]
I think that this is somewhat likely or expected. You could try to use Mavlink FTP as an alternative but it might have the same issue.

The logfile download implementation on PX4 is made in order to maximize the rate and serve the file as fast as possible, usually using the USB 1 interface. You could try to debug that by running `top` in the PX4 console and check just how much CPU is used by mavlink. From the log it looks like your base CPU usage is already at 80%, so then logfile download pushes it do 100%.

![bokeh_plot](https://user-images.githubusercontent.com/1419688/143534984-11e8f3ae-fbb8-4655-b207-6d84c0ed01d1.png)

I don't have a good suggestion except not downloading logfiles while trying to fly, or dive in the PX4 code (or MAVSDK code?) to artificially slow it down.

**Comment by Katawann** [comment]
Hi Julian,

thank you for the clear answer! Actually yes it makes sense that the download try to go as fast as possible. Therefore if I can not interrupt the download, I think the safest way is not to download anything when the drone is in use. 

I will put some energy to have some wake-up hardware/logic for the PX4 + companion computer in order to download the logs when the drone is in the garage of the customer or something like this

Thank you !
