### ISSUE TITLE
Switch CI to Ubuntu 22.04

### ISSUE THREAD

**Issue by julianoes** [mavlink/MAVSDK#1769]
Now that the next Ubuntu LTS release is out, we probably want to move the main support from Ubuntu 20.04 to Ubuntu 22.04. We will keep maintenance for Ubuntu 20.04 as long as it's easily feasible but it's probably soon time to sunset support for 18.04, as its cmake version is outdated anyway.

**Comment by reedev** [comment]
Please keep 18.04 too for a while since JetPack for NVIDIA Jetson is still 18.04. Of course, when the requirement for a more recent cmake for instance is needed, that would be fine imho

**Comment by JonasVautherin** [comment]
Don't we already require a cmake newer than what 18.04 provides? :thinking: 

Anyway I agree with @reedev, IMO we should keep 18.04 until it is end of life (that's 23.04, right?) unless it becomes super tricky to maintain.

**Comment by JonasVautherin** [comment]
Anyway we are usually trying hard to support the Ubuntu LTS, just for cmake we needed the newer cmake at some point, I don't recall why. But e.g. even for tinyxml2 we patch them because their policy is that people should just install the latest cmake, and at least I disagree with it :innocent: : https://github.com/mavlink/MAVSDK/blob/main/third_party/tinyxml2/cmake-3.10.2.patch

**Comment by reedev** [comment]
that's a rather interesting read, thanks

**Comment by julianoes** [comment]
> See the discussion https://github.com/leethomason/tinyxml2/pull/866 if you are interested.

Ha, strong opinions indeed.

**Comment by JonasVautherin** [comment]
https://github.com/mavlink/MAVSDK/pull/1797 goes in that direction.

**Comment by julianoes** [comment]
Let me add it to CI.

**Comment by julianoes** [comment]
I think I did this a while ago.
