### ISSUE TITLE
set_system_status() is not implemented

### ISSUE THREAD

**Issue by vryabokon1705** [mavlink/MAVSDK#2239]
Hi! I am trying to use ServerComponent. I cannot set system status with set_system_status() method. It looks like method is not implemented though it is declared in mavsdk.h file
`_mavSdk->set_system_status(MAV_STATE_ACTIVE);`

I cannot build code with such an instruction with error: 
_undefined reference to `mavsdk::Mavsdk::set_system_status(unsigned char)'_

**Comment by julianoes** [comment]
Odd. Thanks for the note.

So, it was added here:

https://github.com/mavlink/MAVSDK/commit/8d3932dfb7f1395972577167768dc2f57f5c314a

But has since move to `ServerComponent` where it makes a lot more sense.
https://github.com/mavlink/MAVSDK/blob/52fc1c4c440142e4894403047387188a179061e2/src/mavsdk/core/server_component_impl.h#L122

However, it's missing from the public API.

Do you mind making a pull request where you remove it from `mavsdk.h` and add it to `server_component.h`?
