### ISSUE TITLE
Server plugin should not receive commands that are addressed to other components.

### ISSUE THREAD

**Issue by slovak194** [mavlink/MAVSDK#2268]
Hi!

I'm working on multiple cameras using [mavlink camera protocol](https://mavlink.io/en/services/camera.html) as it is [not supported so far](https://mavsdk.mavlink.io/main/en/cpp/api_reference/classmavsdk_1_1_camera.html).

While browsing the source code I've noticed, that it seems the **component_id** field is missing in MAVLinkCommandIntHandlerTableEntry and MAVLinkCommandLongHandlerTableEntry which may be used to filter out commands sent to another component in a system (in a similar way as it is implemented for mavlink_message_handler)

As for now every camera server will process and react to all commands regardless if the component ID matches its own_component_id. For example, if I select camera and subscribe to video_stream_info - all cameras will send ack and video_stream_info message, which seems wrong to me.
This may be simply fixed as it is done [here](https://github.com/mavlink/MAVSDK/blob/30825da62876b8437a9c06f11fe6ad77d79c8136/src/mavsdk/plugins/tracking_server/tracking_server_impl.cpp#L316):
But I'm not sure if this is the right place/level where it has to be done.

Many thanks!

Best regards,
Alex

**Comment by julianoes** [comment]
Thanks for the issue. I think I understand the issue but disagree on the implementation change that you suggest.

The issue is that a server plugin is tied to a component in the first place, so it should not receive commands that are addressed to other components.

The filtering is supposed to happen somewhere in [mavsdk_impl.cpp](https://github.com/mavlink/MAVSDK/blob/30825da62876b8437a9c06f11fe6ad77d79c8136/src/mavsdk/core/mavsdk_impl.cpp#L414) but it's not. I think you're right that components receive all messages, even if they are targeted at other components only.

It looks like that the message handler has the appropriate interface:

https://github.com/mavlink/MAVSDK/blob/973c663f9776130cce9f3cc7b05cb432c4f16254/src/mavsdk/core/mavlink_message_handler.cpp#L26

but it's not used. We need to find a way to use it from server components.

**Comment by julianoes** [comment]
Turns out this component ID filter is to filter for source, for multiple camera plugins (not camera server plugins).

**Comment by julianoes** [comment]
Having looked at this a bit more it looks like your suggestion was pretty close. We don't actually have to add the component ID into the handler table because we can get it from the parent server component.

Can you check if https://github.com/mavlink/MAVSDK/pull/2270 fixes your problem?

**Comment by slovak194** [comment]
Hi Julian,

Many thanks for such quick feedback!

>> The issue is that a server plugin is tied to a component in the first place, so it should not receive commands that are addressed to other components.

That is correct, I've renamed the issue so it does not contain my implementation details and assumptions.

>> Can you check if https://github.com/mavlink/MAVSDK/pull/2270 fixes your problem?

It does! 

Best regards,
Alex

**Comment by julianoes** [comment]
Perfect, thanks for testing.
