### ISSUE TITLE
Issue with SITL Arming

### ISSUE THREAD

**Issue by eanmikale** [mavlink/MAVSDK#855]
Getting the following errors running Python3.7 on Ubuntu 16.04. I believe it is a porting issue. Any assistance would be appreciated. 

await drone.action.arm()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aioconsole-0.1.16.dev0-py3.7.egg/aioconsole/execute.py", line 95, in aexec
    result, new_local = yield from coro
  File "<aexec>", line 2, in __corofn
  File "/usr/local/lib/python3.7/site-packages/mavsdk/generated/action.py", line 167, in arm
    raise ActionError(result, "arm()")
mavsdk.generated.action.ActionError: COMMAND_DENIED_LANDED_STATE_UNKNOWN: 'Command denied, landed state is unknown'; origin: arm(); params: ()

**Comment by JonasVautherin** [comment]
> COMMAND_DENIED_LANDED_STATE_UNKNOWN

I would say that the system is just not ready, i.e. we don't know yet the "landed state" of the drone. What if you wait a bit and try again?

> I believe it is a porting issue.

Nope, it's just an error message because you cannot arm in this state :wink:. Just like you would get an error message if you tried to arm while the drone is flying, or if a command timed out because of a bad connection.

You can just `try... catch` it if you want, and e.g. retry later.
